# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ./disko.nix
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/home/vhs/Data" = {
    device = "/dev/disk/by-uuid/64e4ac0a-e5f2-4e0f-afd7-7eaa772e314f";
    noCheck = true;
    fsType = "ext4";
    options = [
      "users"
      "nofail"
      "noatime"
    ];
  };

  fileSystems."/home/vhs/Data2" = {
    device = "/dev/disk/by-uuid/d536bf84-da2d-49ad-83df-710d3d0daf23";
    noCheck = true;
    fsType = "ext4";
    options = [
      "noatime"
      "nofail"
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
