#! /usr/bin/env zsh

# TODO
# setxkbmap us altgr-intl

xmodmap -e "clear control"
xmodmap -e "clear mod1"
xmodmap -e "clear mod4"
xmodmap -e "keycode 37 = Alt_L Meta_L"
xmodmap -e "keycode 105 = Alt_R Meta_R"
xmodmap -e "keycode 64 = Control_L"
xmodmap -e "keycode 133 = Control_R"
xmodmap -e "add control = Control_L Control_R"
xmodmap -e "add mod1 = Alt_L Meta_L"
xmodmap -e "remove lock = Caps_Lock" # disable capslock functionality from CAPS_LOCK
xmodmap -e "add mod1 = Caps_Lock" #add ALT to capslock
xmodmap -e "keycode 66 = Alt_R" #assign keycode

