#!/usr/bin/env fish

# Example
# export EXA_COLORS="di=96:ln=94:so=91:pi=91:ex=91:bd=91:cd=91:su=91:sg=91:tw=91:ow=91:da=37:ur=92:uw=93:ux=91:gr=92:gw=93:gx=91:tr=92:tw=93:tx=91:sn=36:un=36:ga=36:in=90:hd=36:lp=31:cc=36:bO=36:gm=36:gd=36:gv=36:gt=36:xx=90"

set FILE ~/.zstuff

set BRIGHT_BLACK 90
set BRIGHT_RED 91
set BRIGHT_GREEN 92
set BRIGHT_YELLOW 93
set BRIGHT_BLUE 94
set BRIGHT_MAGENTA 95
set BRIGHT_CYAN 96
set BRIGHT_WHITE 97
set BLACK 30
set RED 31
set GREEN 32
set YELLOW 33
set BLUE 34
set MAGENTA 35
set CYAN 36
set WHITE 37

# ELEMENTS
set DIRECTORY di
set SYMBOLIC_LINK ln
set SOCKET so
set PIPE pi
set EXECUTABLE ex
set BLOCK_DEVICE bd
set CHARACTER_DEVICE cd
set SETUID su
set SETGID sg
set STICKY_WRITABLE tw
set OTHER_WRITABLE ow
set DATE da
set USER_READ_PERMISSION ur
set USER_WRITE_PERMISSION uw
set USER_EXECUTE_PERMISSION ux
set GROUP_READ_PERMISSION gr
set GROUP_WRITE_PERMISSION gw
set GROUP_EXECUTE_PERMISSION gx
set OTHERS_READ_PERMISSION tr
set OTHERS_WRITE_PERMISSION tw
set OTHERS_EXECUTE_PERMISSION tx
set FILE_SIZE sn
set FILE_OWNER un
set GROUP_NAME ga
set INODE_NUMBER in
set HARD_LINK_COUNT hd
set LINK_TARGET_PATH lp
set CONTROL_CHARACTERS cc
set BLOCK_SIZE bO
set GIT_MODIFIED gm
set GIT_DELETED gd
set GIT_RENAMED gv
set GIT_TYPE_CHANGE gt
set PUNCTUATION xx

# COLORS
set -l COLORS
set -a COLORS BRIGHT_BLACK
set -a COLORS BRIGHT_RED
set -a COLORS BRIGHT_GREEN
set -a COLORS BRIGHT_YELLOW
set -a COLORS BRIGHT_BLUE
set -a COLORS BRIGHT_MAGENTA
set -a COLORS BRIGHT_CYAN
set -a COLORS BRIGHT_WHITE
set -a COLORS BLACK
set -a COLORS RED
set -a COLORS GREEN
set -a COLORS YELLOW
set -a COLORS BLUE
set -a COLORS MAGENTA
set -a COLORS CYAN
set -a COLORS WHITE

# ELEMENTS
set -l ELEMENTS
set -a ELEMENTS DIRECTORY
set -a ELEMENTS SYMBOLIC_LINK
set -a ELEMENTS SOCKET
set -a ELEMENTS PIPE
set -a ELEMENTS EXECUTABLE
set -a ELEMENTS BLOCK_DEVICE
set -a ELEMENTS CHARACTER_DEVICE
set -a ELEMENTS SETUID
set -a ELEMENTS SETGID
set -a ELEMENTS STICKY_WRITABLE
set -a ELEMENTS OTHER_WRITABLE
set -a ELEMENTS DATE
set -a ELEMENTS USER_READ_PERMISSION
set -a ELEMENTS USER_WRITE_PERMISSION
set -a ELEMENTS USER_EXECUTE_PERMISSION
set -a ELEMENTS GROUP_READ_PERMISSION
set -a ELEMENTS GROUP_WRITE_PERMISSION
set -a ELEMENTS GROUP_EXECUTE_PERMISSION
set -a ELEMENTS OTHERS_READ_PERMISSION
set -a ELEMENTS OTHERS_WRITE_PERMISSION
set -a ELEMENTS OTHERS_EXECUTE_PERMISSION
set -a ELEMENTS FILE_SIZE
set -a ELEMENTS FILE_OWNER
set -a ELEMENTS GROUP_NAME
set -a ELEMENTS INODE_NUMBER
set -a ELEMENTS HARD_LINK_COUNT
set -a ELEMENTS LINK_TARGET_PATH
set -a ELEMENTS CONTROL_CHARACTERS
set -a ELEMENTS BLOCK_SIZE
set -a ELEMENTS GIT_MODIFIED
set -a ELEMENTS GIT_DELETED
set -a ELEMENTS GIT_RENAMED
set -a ELEMENTS GIT_TYPE_CHANGE
set -a ELEMENTS PUNCTUATION

set -l DEFAULT_COLORS
set -a DEFAULT_COLORS "$DIRECTORY=$BRIGHT_BLACK"
set -a DEFAULT_COLORS "$SYMBOLIC_LINK=$BRIGHT_BLUE"
set -a DEFAULT_COLORS "$SOCKET=$BRIGHT_RED"
set -a DEFAULT_COLORS "$PIPE=$BRIGHT_RED"
set -a DEFAULT_COLORS "$EXECUTABLE=$BRIGHT_RED"
set -a DEFAULT_COLORS "$BLOCK_DEVICE=$BRIGHT_RED"
set -a DEFAULT_COLORS "$CHARACTER_DEVICE=$BRIGHT_RED"
set -a DEFAULT_COLORS "$SETUID=$BRIGHT_RED"
set -a DEFAULT_COLORS "$SETGID=$BRIGHT_RED"
set -a DEFAULT_COLORS "$STICKY_WRITABLE=$BRIGHT_RED"
set -a DEFAULT_COLORS "$OTHER_WRITABLE=$BRIGHT_RED"
set -a DEFAULT_COLORS "$DATE=$WHITE"
set -a DEFAULT_COLORS "$USER_READ_PERMISSION=$BRIGHT_GREEN"
set -a DEFAULT_COLORS "$USER_WRITE_PERMISSION=$BRIGHT_YELLOW"
set -a DEFAULT_COLORS "$USER_EXECUTE_PERMISSION=$BRIGHT_RED"
set -a DEFAULT_COLORS "$GROUP_READ_PERMISSION=$BRIGHT_GREEN"
set -a DEFAULT_COLORS "$GROUP_WRITE_PERMISSION=$BRIGHT_YELLOW"
set -a DEFAULT_COLORS "$GROUP_EXECUTE_PERMISSION=$BRIGHT_RED"
set -a DEFAULT_COLORS "$OTHERS_READ_PERMISSION=$BRIGHT_GREEN"
set -a DEFAULT_COLORS "$OTHERS_WRITE_PERMISSION=$BRIGHT_YELLOW"
set -a DEFAULT_COLORS "$OTHERS_EXECUTE_PERMISSION=$BRIGHT_RED"
set -a DEFAULT_COLORS "$FILE_SIZE=$CYAN"
set -a DEFAULT_COLORS "$FILE_OWNER=$GREEN"
set -a DEFAULT_COLORS "$GROUP_NAME=$MAGENTA"
set -a DEFAULT_COLORS "$INODE_NUMBER=$BRIGHT_BLACK"
set -a DEFAULT_COLORS "$HARD_LINK_COUNT=$CYAN"
set -a DEFAULT_COLORS "$LINK_TARGET_PATH=$RED"
set -a DEFAULT_COLORS "$CONTROL_CHARACTERS=$RED"
set -a DEFAULT_COLORS "$BLOCK_SIZE=$CYAN"
set -a DEFAULT_COLORS "$GIT_MODIFIED=$RED"
set -a DEFAULT_COLORS "$GIT_DELETED=$RED"
set -a DEFAULT_COLORS "$GIT_RENAMED=$YELLOW"
set -a DEFAULT_COLORS "$GIT_TYPE_CHANGE=$YELLOW"
set -a DEFAULT_COLORS "$PUNCTUATION=$BRIGHT_BLACK"
set DEFAULT_LS (string join ":" $DEFAULT_COLORS)

# precedence: existing line in $FILE > $EXA_COLORS env > built-in default
set -l from_file
if test -f $FILE
    set from_file (grep '^EXA_COLORS=' $FILE 2>/dev/null | head -n1 | string replace -r '^EXA_COLORS=' '')
end

if test -n "$from_file"
    set CURRENT_LS $from_file
else if test -n "$EXA_COLORS"
    set CURRENT_LS $EXA_COLORS
else
    set CURRENT_LS $DEFAULT_LS
end

set SELECTED_EL (printf '%s\n' $ELEMENTS | fzf --prompt="Select an element: ")
set -l color_name (printf '%s\n' $COLORS | fzf --prompt="Select a color: ")
set SELECTED_COLOR $$color_name

set -l el_code $$SELECTED_EL

set -l next

for pair in (string split ":" $CURRENT_LS)
    set e (string  split "=" $pair)[1]
    set c (string split "=" $pair)[2]
    if test "$e" = "$el_code"
        set -a next "$e=$SELECTED_COLOR"
    else
        set -a next $pair
    end
end

set x "EXA_COLORS="(string join ":" $next)

if grep -q '^EXA_COLORS=' $FILE 2>/dev/null
    sed -i "s/.*EXA_COLORS.*/$x/" $FILE
else
    echo $x >>$FILE
end
