#!/usr/bin/env fish

# COLORS
set BRIGHT_BLACK 90
set BRIGHT_RED 91
set BRIGHT_GREEN 92
set BRIGHT_YELLOW 93
set BRIGHT_BLUE 94
set BRIGHT_MAGENTA 95
set BRIGHT_CYAN 96
set BRIGHT_WHITE 97
set BLACK 30
set RED 31
set GREEN 32
set YELLOW 33
set BLUE 34
set MAGENTA 35
set CYAN 36
set WHITE 37

# ELEMENTS
set DIRECTORY di
set SYMBOLIC_LINK ln
set SOCKET so
set PIPE pi
set EXECUTABLE ex
set BLOCK_DEVICE bd
set CHARACTER_DEVICE cd
set SETUID su
set SETGID sg
set STICKY_WRITABLE tw
set OTHER_WRITABLE ow
set DATE da
set USER_READ_PERMISSION ur
set USER_WRITE_PERMISSION uw
set USER_EXECUTE_PERMISSION ux
set GROUP_READ_PERMISSION gr
set GROUP_WRITE_PERMISSION gw
set GROUP_EXECUTE_PERMISSION gx
set OTHERS_READ_PERMISSION tr
set OTHERS_WRITE_PERMISSION tw
set OTHERS_EXECUTE_PERMISSION tx
set FILE_SIZE sn
set FILE_OWNER un
set GROUP_NAME ga
set INODE_NUMBER in
set HARD_LINK_COUNT hd
set LINK_TARGET_PATH lp
set CONTROL_CHARACTERS cc
set BLOCK_SIZE bO
set GIT_MODIFIED gm
set GIT_DELETED gd
set GIT_RENAMED gv
set GIT_TYPE_CHANGE gt
set PUNCTUATION xx

# COLORS
set -l COLORS
set -a COLORS BRIGHT_BLACK
set -a COLORS BRIGHT_RED
set -a COLORS BRIGHT_GREEN
set -a COLORS BRIGHT_YELLOW
set -a COLORS BRIGHT_BLUE
set -a COLORS BRIGHT_MAGENTA
set -a COLORS BRIGHT_CYAN
set -a COLORS BRIGHT_WHITE
set -a COLORS BLACK
set -a COLORS RED
set -a COLORS GREEN
set -a COLORS YELLOW
set -a COLORS BLUE
set -a COLORS MAGENTA
set -a COLORS CYAN
set -a COLORS WHITE

# ELEMENTS
set -l ELEMENTS
set -a ELEMENTS DIRECTORY
set -a ELEMENTS SYMBOLIC_LINK
set -a ELEMENTS SOCKET
set -a ELEMENTS PIPE
set -a ELEMENTS EXECUTABLE
set -a ELEMENTS BLOCK_DEVICE
set -a ELEMENTS CHARACTER_DEVICE
set -a ELEMENTS SETUID
set -a ELEMENTS SETGID
set -a ELEMENTS STICKY_WRITABLE
set -a ELEMENTS OTHER_WRITABLE
set -a ELEMENTS DATE
set -a ELEMENTS USER_READ_PERMISSION
set -a ELEMENTS USER_WRITE_PERMISSION
set -a ELEMENTS USER_EXECUTE_PERMISSION
set -a ELEMENTS GROUP_READ_PERMISSION
set -a ELEMENTS GROUP_WRITE_PERMISSION
set -a ELEMENTS GROUP_EXECUTE_PERMISSION
set -a ELEMENTS OTHERS_READ_PERMISSION
set -a ELEMENTS OTHERS_WRITE_PERMISSION
set -a ELEMENTS OTHERS_EXECUTE_PERMISSION
set -a ELEMENTS FILE_SIZE
set -a ELEMENTS FILE_OWNER
set -a ELEMENTS GROUP_NAME
set -a ELEMENTS INODE_NUMBER
set -a ELEMENTS HARD_LINK_COUNT
set -a ELEMENTS LINK_TARGET_PATH
set -a ELEMENTS CONTROL_CHARACTERS
set -a ELEMENTS BLOCK_SIZE
set -a ELEMENTS GIT_MODIFIED
set -a ELEMENTS GIT_DELETED
set -a ELEMENTS GIT_RENAMED
set -a ELEMENTS GIT_TYPE_CHANGE
set -a ELEMENTS PUNCTUATION


set FILE ~/_ls-colors

if test ! -f $FILE
    echo file does not exist, creating...
    cp ~/Public/templates/_ls-colors ~/_ls-colors
    chmod +x ~/_ls-colors
    exit 0
end

set SELECTED_EL (printf '%s\n' $ELEMENTS | fzf --prompt="Select an element: ")
set SELECTED_COLOR (echo '$'(printf '%s\n' $COLORS | fzf --prompt="Select a color: "))


set LINE_NUM (grep -n '\$'"$SELECTED_EL" "$FILE" | cut -d: -f1 | head -n1)
set LINE (sed -n "$LINE_NUM"p "$FILE")

set -l target


for C in $COLORS
    if string match -q "*$C*" "$LINE"
        set target (echo '$'$C)
        break
    end
end


sed -i "$LINE_NUM"s/$target/$SELECTED_COLOR/g $FILE
